apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::678958026205:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1JY3IXC9F6HM
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::678958026205:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-06T21:03:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1369"
  uid: 679d6200-b657-4149-bc32-26cf03eeb137
